### ISSUE TITLE
인터셉터 이슈 

### ISSUE THREAD

**Issue by Ohsaam** [jungtaeyeon/WorkConGW#1]
## ⚠️이슈 내용
- 인터셉터 클래스 구현중 
- 필자는 WebMvcConfig부분을 구현 하려고 했음 -> 근데 패턴에 대한 설계를 잘못함. 그래서 로그인을 해도 홈화면으로 넘어가지 않고 로그인창으로 계속 redirect함.
- PostMan으로 확인 했는데, 값은 잘 넘어옴. (pre/post)handle 이상없음.

## ⚠️이슈 코드

```java
    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new LoginInterceptor())
                .addPathPatterns("/**")
                .addPathPatterns("/common/login")
        registry.addInterceptor(new LoginInterceptor())
                .addPathPatterns("/**")
                .excludePathPatterns("/common/login", "/common/loginForm", "/resources/**", "/attend/insertStartWorkQR", "/m/home");

    }

```

## ✅예상 결과
 특정 url로 접근 시 로그인하면 home으로 넘어가야함.

**Comment by Ohsaam** [comment]
# 해결
- addPathPatterns에대한 이해가 부족했음. `LoginInterceptor` - `Prehandle`에서는 Url로 접근하는 경로에 대해선 해당 인터셉터 부분을 적용시키고(전처리) 
- 그리고 컨트롤러를 경유한 다음 처리되는 `LoginUserLogInterceptor` - `PostHandle`부분을 수정했음.

인터셉터 오타로 인한 오류 (수정 코드)

```java
   public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(new LoginUserLogInterceptor())
                .addPathPatterns("/common/login");

        registry.addInterceptor(new LoginInterceptor())
                .addPathPatterns("/**")
                .excludePathPatterns("/common/login", "/common/loginForm", "/resources/**", "/attend/insertStartWorkQR", "/common/home","/m/home");
        
        registry.addInterceptor(new AdminInterceptor())
                .addPathPatterns("/admin/**")
                .excludePathPatterns("/admin/access_denied");
    }


```

[인터셉터 해결 이슈 ]

![Animation](https://github.com/jungtaeyeon/WorkConGW/assets/96507825/a520bd6c-dfd0-41c5-a098-2f120886b731)


[관리자페이지 Test]
![Animation1](https://github.com/jungtaeyeon/WorkConGW/assets/96507825/63aa527e-9e43-44c6-be04-88b0ed5d2113)

**Comment by woohyungkang** [comment]
이슈 확인했습니다

**Comment by ihwijae** [comment]
이슈 화긴~

**Comment by jungtaeyeon** [comment]
이슈 확인했습니다!
